version: '3.9'
services:
  postgres:
    image: postgres:15.5
    environment:
      POSTGRES_DB: "subscriptions"
      POSTGRES_USER: "subscriptions"
      POSTGRES_PASSWORD: "subscriptions"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - '5433:5432'

  app:
    image: petrov/subscriptions:1.0-SNAPSHOT
    ports:
      - '8080:8080'
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    depends_on:
      postgres:
        condition: service_started